//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson_50_WF_5_v1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lesson_50_WF_5_v1.Resources.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Oops... You lost! There&apos;s no health&quot;.
        /// </summary>
        internal static string lost {
            get {
                return ResourceManager.GetString("lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_ukraine {
            get {
                object obj = ResourceManager.GetObject("map_ukraine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAZE  medal(s): on form -.
        /// </summary>
        internal static string mazeMedalsOnForm {
            get {
                return ResourceManager.GetString("mazeMedalsOnForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , collected by the player -.
        /// </summary>
        internal static string medalsPlayer {
            get {
                return ResourceManager.GetString("medalsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health: .
        /// </summary>
        internal static string tSSLabel1_text {
            get {
                return ResourceManager.GetString("tSSLabel1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps: .
        /// </summary>
        internal static string tSSLabel2_text {
            get {
                return ResourceManager.GetString("tSSLabel2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time: .
        /// </summary>
        internal static string tSSLabel3_text1 {
            get {
                return ResourceManager.GetString("tSSLabel3_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string tSSLabel3_text2 {
            get {
                return ResourceManager.GetString("tSSLabel3_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be a new game.
        /// </summary>
        internal static string txtMsgBox {
            get {
                return ResourceManager.GetString("txtMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation! You won! Exit has found!.
        /// </summary>
        internal static string win_exit {
            get {
                return ResourceManager.GetString("win_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation! You won! Medals are collected!.
        /// </summary>
        internal static string win_medals {
            get {
                return ResourceManager.GetString("win_medals", resourceCulture);
            }
        }
    }
}
